### ISSUE TITLE
resolve with pure dns server fails

### ISSUE THREAD

**Issue by axute** [noglitchyo/dealdoh-client#1] opened 2020-07-26 11:54 UTC
Adding my pihole, docker container with exposed port 53 (UDP & TCP)

```
root@4df8c9d736b0:/app/dealdoh-client# php bin/dealdoh upstream:add "dns://192.168.2.70:53" "local"
 [OK] Added upstream `dns://192.168.2.70:53` successfully.
root@4df8c9d736b0:/app/dealdoh-client# php bin/dealdoh -vvv resolve heise.de A --pretty
 [ERROR] DNS query failed to resolve.
root@4df8c9d736b0:/app/dealdoh-client# ./composer.phar test
> phpunit phpunit.dist.xml
Cannot open file "phpunit.dist.xml.php".
Script phpunit phpunit.dist.xml handling the test event returned with error code 1
root@4df8c9d736b0:/app/dealdoh-client#
```

tested in docker container with:
```
root@4df8c9d736b0:/app/dealdoh-client# ./composer.phar --version
Composer version 1.10.9 2020-07-16 12:57:00
root@4df8c9d736b0:/app/dealdoh-client# php -v
PHP 7.3.20 (cli) (built: Jul 22 2020 10:41:07) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.20, Copyright (c) 1998-2018 Zend Technologies
root@4df8c9d736b0:/app/dealdoh-client#
```

It is also not working with adding "dns://8.8.8.8:53" - but with "https://dns.google.com/resolve" (like your example).

It would be nice if you can fix it.

**Comment by noglitchyo** [comment] 2020-07-27 13:00
Hi @axute,

Thank you for reporting this issue. I easily reproduced what you described. I spotted where the problem is, and I am already working on a fix.

Max

**Comment by noglitchyo** [comment] 2020-08-05 00:22
https://github.com/noglitchyo/dealdoh/pull/5

**Comment by noglitchyo** [comment] 2020-08-05 16:11
Hey,

I am gonna close this issue, which was just fixed in the last release: https://github.com/noglitchyo/dealdoh-client/releases/tag/0.2.0-beta

It should now work correctly with TCP/UDP upstreams and when they are provided with different formats (dns://, udp://, tcp://)
Note that when providing an upstream with the dns:// scheme, the resolver will choose udp:// protocol first and use tcp:// as a fallback if packets sent are too large.

Max

**Closed as completed by noglitchyo** 2020-08-05 16:11 UTC

**Comment by axute** [comment] 2020-08-07 07:16
Thank you very much, i will try out this weekend the new version.
